datamodule:
  image_dir: C:/Users/kcw83/Desktop/fairness/data
  sensitive_attributes: 
  - Male
  - Young
  num_workers: 4
  batch_size: 128

module:
  model:
    num_class: 1
    type: res18
    pretrained_path: None

loss:
  base_loss:
    weight: 1.0
  wd_loss:
    weight: 0.0
    mode: mean
    lcm: False
  gapreg_loss:
    weight: 0.0
    mode: mean
  
trainer:
  learning_rate: 1.0e-03
  epochs: 50
  device: 0
  logger: 
    root: ./runs
    name: vanilla

metric: 
  num_class: 2
  tau: 0.5
  interval: 0.02
